# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eda138cf22f7f3b30c53bf54f6bd1883d165f7fba2fa3d066ad9410a708bcf184ba00b51dcbdece0c575539a5e3a471d844d92f5bf9078b631c50337aca89bae

test:
  secret_key_base: 7d95f46ed4fc3dc874c1c314b83e1d5af2ce4170a2e58976099be968e1ae9ab806abafe6091018083acca17a4b71b90f094a83f617e3c44c601e060b4ed85880

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
